Update Maven_Jenkins_Pipeline

diff --git a/Maven_Jenkins_Pipeline b/Maven_Jenkins_Pipeline
--- a/Maven_Jenkins_Pipeline
+++ b/Maven_Jenkins_Pipeline
@@ -115,8 +115,8 @@ pipeline
                             sshCommand remote: remote, command: 'ls -lrt /var/lib/tomcat/webapps/myapp/'
                             sshCommand remote: remote,
                                                command: "[[ -f /var/lib/tomcat/webapps/myapp/index.html ]] && \
-                                                         echo 'found' || echo 'not found' > /var/lib/tomcat/webapps/myapp/output.txt"
-                            sshGet remote: remote, from: '/var/lib/tomcat/webapps/myapp/output.txt',
+                                                         echo 'found' || echo 'not found' > output.txt"
+                            sshGet remote: remote, from: 'output.txt',
                                                    into: '/var/lib/jenkins/workspace/Maven_HelloWorld_Pipeline_01/output.txt', 
                                                    override: true
                         }
